### ISSUE TITLE
[Refactor] Network 작업 리팩터링

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/MeaningOut-Project#39]
## 개요 및 관련 이슈
Network 기능 리팩터링

| ⚒️ Title | NaverAPI 기능 하나의 객체로 분리하기 | 
| :--- | :--- |
| 📜 **Description** | 현재 ViewController에서 처리하고 있는 NaverAPI기능을 분리하여 처리합니다 |
| 📌 **Issue Number** |  #39 |

### Todos
- [x] Router Pattern으로 URL 구성
- [x] Generic을 이용하여 response 다루기
- [x] URLSession을 이용해서 Network 작업 처리하기
