### ISSUE TITLE
[Refactor] Refactor BaseViewController and BaseView

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/MeaningOut-Project#42]
## 개요 및 관련 이슈
- 현재의 BaseViewController와 BaseView를 수정해서 더 단순하게 동작하는 코드로 수정합니다
- BaseViewController에서 BaseView의 타입을 유추할 수 있도록 합니다
- BaseView의 action과 delegate는 BaseViewController에서 처리할 수 있도록 합니다

| ⚒️ Title |BaseViewController, BaseView 리팩터링| 
| :--- | :--- |
| 📜 **Description** | BaseViewController와 BaseView를 리팩터링 하여 프로젝트의 구조를 깔끔하게 합니다|
| 📌 **Issue Number** |   |

### Todos
- [ ] BaseViewController, BaseView, CodeBaseBuildable 프로토콜 수정
- [ ] Delegate, action을 BaseViewController로 기능을 이전합니다
- [ ] 리팩터링 이후에도 프로젝트의 기능이 달라지지 않게 합니다
