### ISSUE TITLE
[Feat] 비즈니스 로직 분리 연습

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/MeaningOut-Project#45]
## 개요 및 관련 이슈
- 비즈니스 로직을 뷰컨트롤러로부터 분리하는 연습을 해봅니다.

| ⚒️ Title |비즈니스 로직 분리 테스트| 
| :--- | :--- |
| 📜 **Description** | ProfileSettingView에서 비즈니스 로직을 분리하는 연습을 진행합니다|
| 📌 **Issue Number** |  # |

### Todos
- [ ] ProfileSettingViewController의 뷰모델을 생성합니다
- [ ] ProfileSettingViewController의 비즈니스 로직을 뷰모델로 옮길 수 있게 합니다.
- [ ] Model의 변경이 반응형으로 뷰에 적용될 수 있도록 Observable 클래스를 구현합니다
